Myproj/App/urls.py
from django.conf.urls import url
from App import views

app_name='App'

urlpatterns=[

    url(r'^register/',views.register,name='register'),
    
]

Myproj/Myproj/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from App import views


urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^App/',include('App.urls')),
]

Myproj/App/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    Name=models.CharField(max_length=344,unique=True)
    Fav_Movie=models.CharField(max_length=344,unique=True)
    Fav_Book=models.CharField(max_length=344,unique=True)
    Fav_Food=models.CharField(max_length=344,unique=True)

    def __str__(self):
        return self.Name

Myproj/App/forms.py
from App.models import Users
from django import forms

class UserForm(forms.ModelForm):
    class Meta():
        model=Users
        fields='__all__'

        

Myproj/App/views.py
from django.shortcuts import render
from App.forms import UserForm

# Create your views here.
def index(request):
    return render(request,'index.html',{})

def register(request):
    user=UserForm()

    if request.method=="POST":
        user_input=UserForm(request.POST)


        user_input.save(commit=True)
        


    else:
        return render(request,'register.html',{'user':user})

Myproj/templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome</h1>
    <h2>Hala Madrid</h2>

    <img src="{% static "Real.jpg" %}" alt="Oops Not Working">


    <h1>
    <a href="{% url 'App:register' %}">Registration</a>
    </h1>


  </body>
</html>

Myproj/templates/register.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
  </head>
  <body>
    <form  action='{% url 'index'%}' method="POST">
      {% csrf_token %}
      {{ user.as_p }} <br>
      <input type="submit" name="" value="Submit">


    </form>

  </body>
</html>

Myproj/templates/view.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    Thank You
    <a href="{% url 'index' %}">Home Page</a>

  </body>
</html>